version: '3'
services:
  airflow:
    build:
      context: .
      args:
        AIRFLOW_VERSION: 1.10.3
        AIRFLOW_DEPS: "s3,hdfs,async,google_auth"
        PYTHON_DEPS: "statsmodels~=0.9.0 Flask==1.0.3 \
                      boto3~=1.9.198 prometheus_client~=0.7.1 humanfriendly~=4.18 \
                      pylivy~=0.0.3 yarn-api-client~=0.3.6 sasl~=0.2.1 thrift~=0.11.0 \
                      thrift_sasl~=0.3.0 PyHive~=0.6.1"
    image: zomato/airflow:1.10.3
    ports:
    - 8088:8088